export const metadata = {
  title: "Keuangangku",
  description: "Generated by dylanavilla",
};

export default function Head() {
  return (
    <>
      <meta name="theme-color" content="#0f172a" />
      <link rel="manifest" href="/manifest.json" />
      <link rel="icon" href="/icon-192x192.png" />
      <link rel="apple-touch-icon" href="/icon-192x192.png" />
    </>
  );
}
