import { Poppins } from "next/font/google";
import "./globals.css";
import RouterLayouts from "@/components/layout/RouterLayouts";

const myFont = Poppins({
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Keuangangku",
  description: "Generated by dylanavilla",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className}  antialiased`}>
        <RouterLayouts>{children}</RouterLayouts>
      </body>
    </html>
  );
}
